### DISCUSSION TITLE
How to set background to transparent

### DISCUSSION THREAD

**Discussion by JustSimplyKyle** [JakeStanger/ironbar#32] [Q&A] [answered]
This, doesn't work.
![image](https://user-images.githubusercontent.com/68589851/198826179-5b73a1a4-de9a-490d-9bb1-c82b706ff54b.png)
This, however DOES work.
![image](https://user-images.githubusercontent.com/68589851/198826195-4a663bd2-1676-4e5d-bc79-4de6798541ba.png)
But it also has the caveat of transparenting the popup window.
![image](https://user-images.githubusercontent.com/68589851/198826228-e7644543-b08a-45d9-b9a5-ef7ee22031c4.png)
This is my `style.css`
https://0x0.st/oY-y.css

**Comment by JakeStanger** [comment, marked as answer]
If you want to target the container and everything inside the container, you could use:

```css
.container, .container * {
  background-color: rgba(0, 0, 0, 0);
}
```

That will recursively set the background on all children and their children. 

If you want to target only the first layer of children:
```css
.container, .container > * {
  background-color: rgba(0, 0, 0, 0);
}
```

If needed you could then set the colour back on each widget.

EDIT: Transparency needs to be set on the window, which can be done using the `.background` class:
```css
.background {
  background-color: rgba(0, 0, 0, 0);
}
```

**Reply by JustSimplyKyle** [reply]
Still doesn't work, but surprisingly, both these two solutions still will transparent the pop-up window
![image](https://user-images.githubusercontent.com/68589851/198829459-8e0d0faf-543a-41c2-9bc7-296f6e7b6d8b.png)

**Reply by JakeStanger** [reply]
Hm okay that's unexpected. Could you share your current config & css please, and I'll have a play

**Reply by JustSimplyKyle** [reply]
https://0x0.st/oY4H.corn
https://0x0.st/oY48.css

**Reply by JakeStanger** [reply]
Aha, cracked it. So you need to add the transparency onto the top-level background:

```css
.background {
  background-color: rgba(0, 0, 0, 0);
}
```
I'll make sure that selector gets added to the wiki.

And it makes sense this was adding transparency to the menus:
```css
.container, .container * {
  background-color: rgba(0, 0, 0, 0);
}
```
Since that's saying "target the container and every element inside the container at any depth". On everything else, you're explicitly overruling that with another background colour, but the menu background aren't specified anywhere so abide by that rule. 

CSS is an adventure.

Btw, love the gradients! Would be awesome if I can add your config/style to a showcase when it's finished.
