### DISCUSSION TITLE
Custom keyboard layout display

### DISCUSSION THREAD

**Discussion by alejandro-llanes** [JakeStanger/ironbar#724] [Show and tell]
A simple label showing current keyboard layout.

```toml
[[end]]
type = "script"
cmd = "hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap'"
mode = "poll"
interval = 5000
tooltip = "{{300000:hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .layout +\" \\n \"+.options' }}"
```
