### DISCUSSION TITLE
[desktop] [sway] flat simple transparent bar

### DISCUSSION THREAD

**Discussion by ToxicMushroom** [JakeStanger/ironbar#771] [Show and tell]
## preview
![image](https://github.com/user-attachments/assets/76cb0987-de08-4dc9-8e21-870dc024cd0e)
![image](https://github.com/user-attachments/assets/4ee135e6-db7b-42a9-85dd-fc0e92a000df)
![image](https://github.com/user-attachments/assets/67e125ca-1bf6-4173-97c5-2061463929ef)

## configs

<details><summary>config.toml</summary>

```toml
name = "bar"
anchor_to_edges = true
height = 42
position = "top"

[[start]]
type = "workspaces"
all_monitors = false
on_scroll_up = "swaymsg workspace prev_on_output"
on_scroll_down = "swaymsg workspace next_on_output"

[[end]]
type = "sys_info"
format = [
    "⟮  {cpu_percent}% {temp_c:k10temp-Tccd2}°C⟯",
    "⟮  {memory_percent}%⟯",
    "⟮󰋊 {disk_percent:/}%⟯",
    "⟮󰓢 {net_down:eno1} / {net_up:eno1} Mbps⟯",
]

[end.interval]
memory = 30
cpu = 1
temps = 5
disks = 300
networks = 3

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 100
on_scroll_up = "pactl set-sink-volume @DEFAULT_SINK@ +10%"
on_scroll_down = "pactl set-sink-volume @DEFAULT_SINK@ -10%"

[end.icons]
volume_high = "󰕾"
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"

[end.truncate]
mode = "end"
length = 50

[[end]]
type = "clock"
format = "  %H:%M:%S %d/%m/%Y"

[[end]]
type = "tray"
direction = "left_to_right"

[[start]]
type = "sway_mode"

[[end]]
type = "notifications"
show_count = true

[end.icons]
closed_none = "󰍥"
closed_some = "󱥂"
closed_dnd = "󱅯"
open_none = "󰍡"
open_some = "󱥁"
open_dnd = "󱅮"
```
</details>

<details><summary>style.css</summary>

```css
@define-color color_bg alpha(#2d2d2d, 0.7);
@define-color color_bg_dark alpha(#1c1c1c, 0.7);
@define-color color_border alpha(#424242, 0.7);
@define-color color_border_active alpha(#6699cc, 0.7);
@define-color color_text #ffffff;
@define-color color_urgent #8f0a0a;

/* -- base styles -- */

* {
    font-family: CaskaydiaCove Nerd Font, sans-serif;
    font-size: 16px;
    text-shadow: none;
    border: none;
    border-radius: 0;
    opacity: 1.0;
}
.background {
    background-color: rgba(0, 0, 0, 0);
}

button, label {
    box-shadow: none;
    background: none;
    background-color: rgba(0, 0, 0, 0);
    color: @color_text;
}

button:hover {
    background-color: @color_bg_dark;
}

#bar {
    background-color: @color_bg;
    background-image: none;
    box-shadow: none;
}

.popup {
    border: 1px solid @color_border;
    padding: 1em;
}

/* -- gtkscale -- */
scale trough {
    border-radius: 4px;
    background-color: #535854;
}

scale trough highlight {
    border-radius: 4px;
    background-color: #96b9d0;
}

scale value {
    color: #ffffff;
}

scale trough slider {
    color: purple;
    background-color: purple;
}

.popup-volume .slider slider {
    background-color: #D9DDDC;
    border-radius: 15;
    border: 2px outset gold;
    background-image: none;
}

/* -- clipboard -- */

.clipboard {
    margin-left: 5px;
    font-size: 1.1em;
}

.popup-clipboard .item {
    padding-bottom: 0.3em;
    border-bottom: 1px solid @color_border;
}

.popup-clipboard {
    background-color: @color_bg;
}


/* -- clock -- */

.clock {
    font-weight: bold;
    margin-left: 5px;
}

.popup-clock .calendar-clock {
    color: @color_text;
    font-size: 2.5em;
    padding-bottom: 0.1em;
}

.popup-clock {
    background-color: @color_bg;
    color: @color_text;
}

.popup-clock .calendar .header {
    padding-top: 1em;
    border-top: 1px solid @color_border;
    font-size: 1.5em;
}

.popup-clock .calendar:selected {
    background-color: @color_border_active;
}

/* notifications */

.notifications .count {
    font-size: 1rem;
    font-weight: bold;
    background-color: #DA373C;
    color: white;
    border-radius: 100%;
    margin-right: 3px;
    margin-top: 3px;
    padding-left: 5px;
    padding-right: 5px;
    opacity: 1;
}

/* -- script -- */

.script {
    padding-left: 10px;
}


/* -- sys_info -- */

.sysinfo {
    margin-right: 10px;
}

.sysinfo .item {
    margin-left: 5px;
}


/* -- tray -- */

.tray {
    background-color: rgba(0,0,0,0);
    margin-left: 10px;
}
.tray menu {
    background-color: rgba(0,0,0, 0.7);
    padding: 8px 0;
}
/* Overrides the label text just for the tray */
.tray label {
    /* color: black; */
}

/* -- volume -- */

.popup-volume .device-box {
    border-right: 1px solid @color_border;
}

.popup-volume {
    background-color: @color_bg;
}

/* -- power -- */

.popup-upower {
    background-color: @color_bg;
}

/* -- workspaces -- */

.workspaces .item.focused {
    box-shadow: inset 0 -3px;
    background-color: @color_bg_dark;
}

.workspaces .item:hover {
    box-shadow: inset 0 -3px;
}

/* -- upower -- */
.upower .icon {
    opacity: 0;
}

.upower .contents {
    color: @color_text;
}
```
</details>
