### ISSUE TITLE
CSS background not rendering:

### ISSUE THREAD

**Issue by Phant80m** [JakeStanger/ironbar#100]
![image](https://user-images.githubusercontent.com/70614900/230352374-3ce27c89-3b7d-402b-921c-518772382a3b.png)
the style is not registering for background-color,
![image](https://user-images.githubusercontent.com/70614900/230352630-a4ed5e75-d594-49e0-a5b0-e622749b27f3.png)
and for some reason its registering under the button. settings for .item does nothing

OS:
archlinux-EndevourOS

**Comment by JakeStanger** [comment]
Styling just `#workspaces` will style the box that the buttons are inside of, so that's working as I'd expect.

Using `#workspaces .item` definitely works for me. This is what I have in my stylesheet:

```css
#bar {
    border-top: 1px solid #424242;
}

.background, .container {
    background-color: #2d2d2d;
}

#workspaces .item {
    color: white;
    background-color: #2d2d2d;
    border-radius: 0;
}
```

If you can't get anywhere with the above, can you share your config and css (as text) please and I can have a play?
