### ISSUE TITLE
All Ironbar instances show up in a single screen

### ISSUE THREAD

**Issue by uttarayan21** [JakeStanger/ironbar#1042]
**Describe the bug**
When I put the display to sleep and then resume all ironbar instances show on my primary monitor.

**To reproduce**
On hyprland with multiple monitors
1. `hyprland display dpms`
2. Wait an undetermined amount of time (usually it takes a while)
3. Move mouse to wake

**Expected behavior**
The system is same as how it was when the displays were turned off.

**System information:**
- Distro: NixOS 25.11 Unstable
- Compositor: Hyprland
- Ironbar version:  0.16.1

**Configuration**

<details><summary>Config</summary>

```
{
  "monitors": {
    "DP-1": {
      "end": [
        {
          "type": "clock"
        }
      ],
      "icon_theme": "Papirus-Dark",
      "position": "bottom",
      "start": [
        {
          "show_icons": true,
          "show_names": false,
          "type": "launcher"
        },
        {
          "type": "focused"
        }
      ]
    },
    "DP-3": {
      "end": [
        {
          "max_items": 3,
          "truncate": {
            "length": 50,
            "mode": "end"
          },
          "type": "clipboard"
        },
        {
          "player_type": "mpris",
          "type": "music"
        },
        {
          "type": "clock"
        }
      ],
      "position": "bottom",
      "start": [
        {
          "favourites": [
            "firefox",
            "discord"
          ],
          "show_icons": true,
          "show_names": false,
          "type": "launcher"
        },
        {
          "type": "focused"
        }
      ]
    },
    "HDMI-A-1": {
      "end": [
        {
          "format": [
            "  CPU {cpu_percent}% | {temp_c:coretemp-Package-id-0}°C",
            "  RAM {memory_used}GB/{memory_total}GB"
          ],
          "interval": {
            "cpu": 1,
            "memory": 30,
            "temps": 5
          },
          "type": "sys_info"
        },
        {
          "type": "tray"
        }
      ],
      "icon_theme": "Papirus-Dark",
      "position": "bottom",
      "start": [
        {
          "all_monitors": true,
          "favorites": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10"
          ],
          "name_map": {
            "1": "icon:foot",
            "10": "icon:spotify",
            "2": "icon:code",
            "3": "icon:firefox",
            "4": "icon:slack",
            "5": "icon:steam",
            "6": "icon:misc",
            "7": "icon:misc",
            "8": "icon:firefox",
            "9": "icon:discord"
          },
          "type": "workspaces"
        }
      ]
    }
  }
}

```

</details>

<details><summary>Styles</summary>

```css
/*
*
* Catppuccin Mocha palette
* Maintainer: rubyowo
*
*/

@define-color base   #1e1e2e;
@define-color mantle #181825;
@define-color crust  #11111b;

@define-color text     #cdd6f4;
@define-color subtext0 #a6adc8;
@define-color subtext1 #bac2de;

@define-color surface0 #313244;
@define-color surface1 #45475a;
@define-color surface2 #585b70;

@define-color overlay0 #6c7086;
@define-color overlay1 #7f849c;
@define-color overlay2 #9399b2;

@define-color blue      #89b4fa;
@define-color lavender  #b4befe;
@define-color sapphire  #74c7ec;
@define-color sky       #89dceb;
@define-color teal      #94e2d5;
@define-color green     #a6e3a1;
@define-color yellow    #f9e2af;
@define-color peach     #fab387;
@define-color maroon    #eba0ac;
@define-color red       #f38ba8;
@define-color mauve     #cba6f7;
@define-color pink      #f5c2e7;
@define-color flamingo  #f2cdcd;
@define-color rosewater #f5e0dc;
@define-color color_bg @base;
@define-color color_bg_dark @mantle;
@define-color color_border @crust;
@define-color color_border_active @mauve;
@define-color color_text #ffffff;
@define-color color_urgent @lavender;

/* -- base styles -- */

* {
  font-family: Noto Sans Nerd Font, sans-serif;
  font-size: 16px;
  border: none;
  border-radius: 0;
}

box, menubar, button {
  background-color: @color_bg;
  background-image: none;
}

button, label {
  color: @color_text;
}

button:hover {
  background-color: @color_bg_dark;
}

#bar {
  border-top: 1px solid @color_border;
}

.popup {
  border: 1px solid @color_border;
  padding: 1em;
}


/* -- clipboard -- */

.clipboard {
  margin-left: 5px;
  font-size: 1.1em;
}

.popup-clipboard .item {
  padding-bottom: 0.3em;
  border-bottom: 1px solid @color_border;
}


/* -- clock -- */

.clock {
  font-weight: bold;
  margin-left: 5px;
}

.popup-clock .calendar-clock {
  color: @color_text;
  font-size: 2.5em;
  padding-bottom: 0.1em;
}

.popup-clock .calendar {
  background-color: @color_bg;
  color: @color_text;
}

.popup-clock .calendar .header {
  padding-top: 1em;
  border-top: 1px solid @color_border;
  font-size: 1.5em;
}

.popup-clock .calendar:selected {
  background-color: @color_border_active;
}


/* -- launcher -- */

.launcher .item {
  margin-right: 4px;
}

.launcher .item:not(.focused):hover {
  background-color: @color_bg_dark;
}

.launcher .open {
  border-bottom: 1px solid @color_text;
}

.launcher .focused {
  border-bottom: 2px solid @color_border_active;
}

.launcher .urgent {
  border-bottom-color: @color_urgent;
}

.popup-launcher {
  padding: 0;
}

.popup-launcher .popup-item:not(:first-child) {
  border-top: 1px solid @color_border;
}


/* -- music -- */

.music:hover * {
  background-color: @color_bg_dark;
}

.popup-music .album-art {
  margin-right: 1em;
}

.popup-music .icon-box {
  margin-right: 0.4em;
}

.popup-music .title .icon, .popup-music .title .label {
  font-size: 1.7em;
}

.popup-music .controls *:disabled {
  color: @color_border;
}

.slider slider {
  color: @color_urgent;
  background-color: @color_urgent;
}

.popup-music .volume .slider slider {
  border-radius: 100%;
}

.popup-music .volume .icon {
  margin-left: 4px;
}

.popup-music .progress .slider slider {
  border-radius: 100%;
}

/* -- script -- */

.script {
  padding-left: 10px;
}


/* -- sys_info -- */

.sysinfo {
  margin-left: 10px;
}

.sysinfo .item {
  margin-left: 5px;
}


/* -- tray -- */

.tray {
  margin-left: 10px;
}


/* -- workspaces -- */

.workspaces .item.focused {
  box-shadow: inset 0 -3px;
  background-color: @color_bg_dark;
}

.workspaces .item:hover {
  box-shadow: inset 0 -3px;
}


/* -- custom: power menu -- */

.popup-power-menu #header {
  font-size: 1.4em;
  padding-bottom: 0.4em;
  margin-bottom: 0.6em;
  border-bottom: 1px solid @color_border;
}

.popup-power-menu .power-btn {
  border: 1px solid @color_border;
  padding: 0.6em 1em;
}

.popup-power-menu #buttons > *:nth-child(1) .power-btn {
  margin-right: 1em;
}

```

</details>

**Additional context**
Usually happens after a while and not If I immediately the display on and off
Doing 
`systemctl --user restart ironbar`
 fixes the issue
**Screenshots**

![Image](https://github.com/user-attachments/assets/385b806e-63ce-4684-814c-52612fae258f)
