### ISSUE TITLE
Changing the monitor in the config breaks my css

### ISSUE THREAD

**Issue by HenrySteinmetz** [JakeStanger/ironbar#108]
**Describe the bug**
> When I try to make my bar only appear on one screen with the TOML config file my css completely breaks

**To Reproduce**
1. Use a Toml config
2. Start the config with `[monitors] [monitors.DP-1] `

**Expected behavior**
> The bar should appear one only one screen (which works fine) with the style set in the stylesheet

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland
 - Ironbar version: 0.11.0
#
**Configuration**
<details><summary>Config</summary>

```

[monitors]
[monitors.DP-1]

position = 'top'
margin.left = 10
margin.right = 10
margin.top = 10
height = 32

[[start]]
type = 'workspaces'
all_monitors = true

[start.name_map]
1 = '1'
2 = '2'
3 = '3'
4 = '4'
5 = '5'
6 = '6'
7 = '7'
8 = '8'
9 = '9'

```

</details>

<details><summary>Styles</summary>

```css
@import url("colors.css");

#workspaces {
  border-radius: 25px;
  border-color: @bga;
  background-color: @bga;
}

#workspaces .item {
  color: @text;
  background-color: @bga;
}

#workspaces .item.focused {
  background-color: @bga;
  color: @mauve;
}

```

```css
@import url("colors.css");

#workspaces {
  border-radius: 25px;
  border-color: @bga;
  background-color: @bga;
}

#workspaces .item {
  color: @text;
  background-color: @bga;
}

#workspaces .item.focused {
  background-color: @bga;
  color: @mauve;
}
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/121169024/232240609-1ae3b18d-20d1-4c08-95d9-a6cb4308353d.png)
![image](https://user-images.githubusercontent.com/121169024/232240787-22949336-531d-43d8-931a-2e11ec362008.png)
