### ISSUE TITLE
Help with styling `.workspaces`

### ISSUE THREAD

**Issue by dennkaii** [JakeStanger/ironbar#170]
border-raidus in .workspaces  aint working

OS:
![image](https://github.com/JakeStanger/ironbar/assets/70287696/1afdf48d-b9e3-4e61-aca9-e68023b04a66)

**Screenshots**
![image](https://github.com/JakeStanger/ironbar/assets/70287696/3608f722-55a2-4704-9647-54de46e2bea8)

**Comment by JakeStanger** [comment]
CSS is case-sensitive, so you need to use `.workspaces` and not `.Workspaces`. Let me know if you still have any trouble.

**Comment by dennkaii** [comment]
still 
![image](https://github.com/JakeStanger/ironbar/assets/70287696/bd540024-2e7a-4ace-bbad-7073691c3be3)

**Comment by JakeStanger** [comment]
So this looks to be a quirk in how GTK handles border-radius with buttons. It does apply to the container, but the child buttons aren't "cropped" to the container.

I think you can achieve what you want here with a bit of padding on the  `.workspaces`, so that you have some room on the edges to curve. Something like the below should work:

```css
.container, window {
  border-radius: 10px;
  background-color: rgba(0, 0, 0, 0);
}

.workspaces {
  background-color: #ccc;
  padding: 0 10px; 
  border-radius: 10px;
}

.workspaces .item {
  background-color: #ccc;
  border: none;
}
```

**Comment by A-Cloud-Ninja** [comment]
Alternatively, my solution to default GTK styling on most of the widgets is to use something like
```css
* {
  border: none;
  border-radius: 0;
  border-image: none;
  outline: none;
  background-image: none;
  box-shadow: none;
  color: inherit;
}
```
I throw this at the top of my CSS and it removes quite a bit of the default button styling and such.
