### ISSUE TITLE
Last app is displayed in focused module when no app is available on Hyprland

### ISSUE THREAD

**Issue by kepi** [JakeStanger/ironbar#337]
**Describe the bug**

This happens when I open new workspace or simply close only window on some workspace. Focused module doesn't clear itsef and I'm stuck with previous title.

**To Reproduce**
1. start new hyprland session with ironbar with focused module on
2. open any app with title
3. close the app

**Expected behavior**

I expect focused module to be empty or dissappear.

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland
 - Ironbar version: v0.13.0.r74.gc2306d6-1

**Configuration**

<details><summary>Config</summary>

```yaml
center:
  - type: focused
    icon_size: 16
    truncate:
      mode: start

```
</details>
