### ISSUE TITLE
workspaces: favorites are missing .inactive unless switched to

### ISSUE THREAD

**Issue by eclairevoyant** [JakeStanger/ironbar#390]
**Describe the bug**

On Sway, the workspaces module doesn't appear to correctly style the favorites (apply `.inactive` class) unless I switch to them and back.

**To Reproduce**
1. Kill and start bar
2. Favorites are not styled correctly
3. Switch to a favorite workspace with no windows
4. Switch to another workspace
5. Previous favorite is now styled correctly

**Expected behavior**
Favorite workspaces should have `.inactive` applied from the start.

**System information:**
 - Distro: NixOS 24.05pre
- Compositor: Sway
 - Ironbar version: 0.13.0

**Configuration**

<summary>Config</summary>

```

```

<summary>Styles</summary>

```css
.workspaces .item.focused {
    background-color: #ffffff;
}
  
.workspaces .item.focused label {
    color: #000000;
}
  
.workspaces .item.inactive {
    background-color: #000000;
}
```

**Additional context**
n/a

**Screenshots**

First 3 workspaces have windows open, the rest are favorites.

Top is **ironbar**
Bottom is **waybar**, as a reference of expected behaviour with persistent workspaces

Recording at https://imgur.com/a/EhBE6X3
