### ISSUE TITLE
The icon theme is not use in the Focused module

### ISSUE THREAD

**Issue by bluebyt** [JakeStanger/ironbar#485]
**Describe the bug**
The icon theme is not use in the Focused module and around half of apps I have message that Ironbar failed to find image.

**To Reproduce**
Set the icon theme in the focused module.
icon_theme = "Tela-circle-nord" 
The path of icon theme is: /home/bluebyt/.local/share/icons/Tela-circle-nord/

**Expected behavior**
Use the Icon theme Tela-circle-nord

**System information:**
- Distro: Arch Linux
- Compositor: Wayfire
- Ironbar version: 0.15.0-pre

Error message in the terminal:
**Additional context**
find image: org.gnome.TextEditor org.gnome.TextEditor
2024-03-04T18:39:51.730084Z  WARN ironbar::image::provider: 130: Failed to find image: tilix com.gexperts.Tilix
2024-03-04T18:39:54.055970Z  WARN ironbar::image::provider: 130: Failed to find image: tilix com.gexperts.Tilix
2024-03-04T18:39:54.646231Z  WARN ironbar::image::provider: 130: Failed to find image: totem org.gnome.Totem
2024-03-04T18:39:56.319687Z  WARN ironbar::image::provider: 130: Failed to find image: org.gnome.Ptyxis.Devel org.gnome.Ptyxis.Devel
2024-03-04T18:39:56.856353Z  WARN ironbar::image::provider: 130: Failed to find image: evolution org.gnome.Evolution
2024-03-04T18:40:00.303476Z  WARN ironbar::image::provider: 130: Failed to find image: com.github.rafostar.Clapper com.github.rafostar.Clapper
2024-03-04T18:40:00.849645Z  WARN ironbar::image::provider: 130: Failed to find image: org.gnome.Nautilus org.gnome.Nautilus
2024-03-04T18:40:02.351272Z  WARN ironbar::image::provider: 130: Failed to find image: gthumb org.gnome.gThumb

**Configuration**

<details><summary>Config</summary>

```
let {
    $tray = { type = "tray" }
  $clock = {
    type = "clock"
    format = "%a, %H:%M:%S"
   // format = "%d/%m/%Y %H:%M"
  }
   
    $window = {
      type = "focused"
      show_icon = true
      show_title = true
      icon_size = 24
      icon_theme = "Tela-circle-nord" 
      truncate.mode = "end"
      truncate.max_length = 25
    }
    
    $SysInfo = { 
    type = "sys_info"
    interval.memory = 30
    interval.cpu = 1
    interval.temps = 3
    interval.disks = 300
    interval.networks = 3
      
     format = [
      " {temp_c:coretemp-Package-id-0}°C "
      " {disk_free:/}GB "
      " {memory_percent}% "
      " {cpu_percent}% "
    ]
    
    }

    $cava = {
        transition_type = "slide_end"
        transition_duration = 750
        name = "cava"
        type = "script"
        mode = "watch"
        cmd = "/home/bluebyt/.config/ironbar/scripts/cava"
   }
  

   $mpris = {
        type = "music"
        player_type = "mpris"

        on_click_middle = "playerctl play-pause"
        on_scroll_up = "playerctl volume +5"
        on_scroll_down = "playerctl volume -5"

    }

    $mpd_local = { type = "music" player_type = "mpd" music_dir = "/home/bluebyt/Music" truncate.mode = "end" truncate.max_length = 100 }
    $mpd_server = { type = "music" player_type = "mpd" host = "127.0.0.1:6600" truncate = "end" }

    $volume = {
        transition_type = "slide_end"
        transition_duration = 350
        type = "custom"
        bar = [ 
            {
                type = "slider"
                class = "scale"
                length = 100
                max = 100
                on_change = "!wpctl set-volume @DEFAULT_SINK@ $0%"
                on_scroll_down = "wpctl set-volume @DEFAULT_SINK@ 2%-"
                on_scroll_up = "wpctl set-volume @DEFAULT_SINK@ 2%+"
                on_click_right = "pavucontrol"
                value = "100:/home/bluebyt/.config/ironbar/scripts/volume"
                tooltip = "{{/home/bluebyt/.config/ironbar/scripts/volume}}%"
            }
        ]
    }

    $workspace = {
        type = "workspaces"
        sort = "alphanumeric"
        on_scroll_up = "hyprctl dispatch workspace -1"
        on_scroll_down = "hyprctl dispatch workspace +1"
    }
    $wlogout = {
        type = "custom"
        bar = [ 
            {
                type = "button"
                name = "wlogout"
                class = "wlogout"
                label = ""
                on_click = "!~/.config/ironbar/scripts/wlogout"
            }
        ]
    }
    
    $pacman = {
        type = "custom"
        bar = [ 
            {
                type = "label"
                name = "pacman"
                class = "pacman"
                label = " {{90000:checkupdates | wc -l}} packages"               
            }
        ]
    }
    
    
    
    $start = [ $mpd_local $cava]
    $center = [ $window ]
    $end = [ $volume $pacman $SysInfo $clock $wlogout]
}
in {
        position = "top"
        start = $start
        center = $center
        end = $end
}
```
</details>

<details><summary>Styles</summary>

```css

@define-color color_bg #2e3440;
@define-color color_bg_dark #292e39;
@define-color color_border #424242;
@define-color color_border_active #b48ead;
@define-color color_text #aec0d5;
@define-color color_urgent #8f0a0a;

.container {
  font-family: Roboto Mono SemiBold;
  font-weight: bold;
  font-size: 20px;
}

#cava {
  font-family: renogare;
}

.clock {
  font-size: 10px;
  font-weight: normal;
  padding: 0px 10px 0px 10px;
  background: linear-gradient(45deg, rgb(235,203,139) 0%, rgb(208,135,112) 50%, rgb(180, 142, 173) 100%);
  background-size: 300% 300%;
  animation: gradient 2s ease infinite;
  text-shadow: 0px 0px 5px rgba(0, 0, 0, 0.377);
  box-shadow: rgba(0, 0, 0, 0.288) 2px 2px 5px 2px;
  border-radius: 16px;
  margin: 10px 10px 10px 10px;
  font-family: Roboto Mono SemiBold;
}

.clock_date {
  font-family: Roboto Mono SemiBold;
  font-weight: normal;
  font-size: 18px;
  color: rgb(94,129,172);
}


.background {
  background-color: rgba(0, 0, 0, 0)
}

/* base */
.sysinfo .item,
.script,
.tray {
  padding: 0px 10px;
  margin-top: 10px;
  margin-bottom: 10px;
  margin-right: 10px;
  border-radius: 15px;
  background: #88c0d0;
  color: #516079;
  box-shadow: rgba(0, 0, 0, 0.116) 2px 2px 5px 2px;
}

.pacman,
.wlogout {
  padding: 0px 10px;
  margin-top: 10px;
  margin-bottom: 10px;
  margin-right: 10px;
  border-radius: 15px;
  background: #a3be8c;
  color: #516079;
  font-size: 20px;
  box-shadow: rgba(0, 0, 0, 0.116) 2px 2px 5px 2px;
}

.scale,
.internet,
.script {
  transition: all 0.5s cubic-bezier(0.5, 1, 0.89, 1);
  margin-top: 10px;
  margin-bottom: 10px;
  margin-right: 10px;
  padding-right: 20px;
  padding-left: 20px;
  padding-bottom: 3px;
  box-shadow: rgba(0, 0, 0, 0.288) 2px 2px 5px 2px;
  text-shadow: 0px 0px 5px rgba(0, 0, 0, 0.377);
  border-radius: 15px;
  background: rgb(202, 158, 230);
  background: linear-gradient(45deg, rgba(202, 158, 230, 1) 0%, rgba(245, 194, 231, 1) 43%, rgba(180, 190, 254, 1) 80%, rgba(137, 180, 250, 1) 100%);
  background-size: 300% 300%;
  animation: gradient 5s ease infinite;
  color: #fff;
}


scale trough {
  border-radius: 16px;
  background-color: #E7D4CB;
  box-shadow: 0 2px 3px 2px rgba(00, 00, 00, 0.4);
  min-height: 10px;
  min-width: 70px;
  margin: 0px 5px 10px 10px;
}

scale value {
  color: #77a5bf;
  font-size: 0px;
}

scale trough highlight {
  background-image: linear-gradient(to right, #afcee0 30%, #92B6F4 50%, #77a5bf 100%);
  border-radius: 10px;
  background-color: #afcee0;
}

.focused {
  color: rgb(84, 111, 175);
  font-size: 20px;
  padding: 0px 10px 0px 10px;
  margin: 10px 10px 10px 0px;
  background: rgb(238, 190, 190);
  background: linear-gradient(45deg, rgb(244, 219, 214) 0%, rgb(223, 221, 238) 43%, rgb(245, 208, 225) 100%);
  background-size: 300% 300%;
  animation: gradient 2s ease infinite;
  border-radius: 16px;
}


/* cpu */
.sysinfo .item:nth-child(1) {
  background: rgb(180, 190, 254);
  background: linear-gradient(52deg, rgba(180, 190, 254, 1) 0%, rgba(137, 220, 235, 1) 32%, rgba(137, 180, 250, 1) 72%, rgba(166, 227, 161, 1) 100%);
  background-size: 300% 300%;
  animation: gradient 20s ease infinite;
  text-shadow: 0px 0px 5px rgba(0, 0, 0, 0.377);
  /* background-color: #b4befe; */
  color: #fff;
}

.music,
.clock {
  margin-top: 10px;
  margin-bottom: 10px;
  margin-right: 10px;
  padding-right: 20px;
  padding-left: 20px;
  padding-bottom: 3px;
  box-shadow: rgba(0, 0, 0, 0.288) 2px 2px 5px 2px;
  text-shadow: 0px 0px 5px rgba(0, 0, 0, 0.377);
  border: none;
  border-radius: 15px;
  font-size: 20px;
  background: rgb(202, 158, 230);
  background: linear-gradient(45deg, rgba(202, 158, 230, 1) 0%, rgba(245, 194, 231, 1) 43%, rgba(180, 190, 254, 1) 80%, rgba(137, 180, 250, 1) 100%);
  background-size: 300% 300%;
  animation: gradient 10s ease infinite;
  color: #fff;
}

/* -- music -- */

.music .contents


.popup-music

.tray {
  color: rgb(84, 111, 175);
  font-size: 15px;
  padding: 0px 10px 0px 10px;
  margin: 10px 10px 10px 0px;
  background: rgb(238, 190, 190);
  background: linear-gradient(45deg, rgb(244, 219, 214) 0%, rgb(223, 221, 238) 43%, rgb(245, 208, 225) 100%);
  background-size: 300% 300%;
  animation: gradient 5s ease infinite;
  border-radius: 16px;
}

.tray>.passive {
  -gtk-icon-effect: dim;
}

.tray>.needs-attention {
  -gtk-icon-effect: highlight;
  background-color: #eb4d4b;
}

.workspaces {
  font-family: Renogare;
  font-weight: normal;
  font-size: 25px;
  font-weight: normal;
  margin: 10px 0px 0px 20px;
  border-radius: 16px;
}

.workspaces .item {
  box-shadow: rgba(0, 0, 0, 0.116) 2px 2px 5px 2px;
  border: unset;
  background: #fff;
  border-radius: 15px;
  margin: 10px 10px 15px 0px;
  padding: 5px 20px 5px 20px;
  color: #cba6f7;
}

.workspaces .item.focused {
  border: unset;
  font-size: 25px;
  transition: all 0.5s cubic-bezier(0.5, 1, 0.89, 1);
  box-shadow: rgba(0, 0, 0, 0.288) 2px 2px 5px 2px;
  text-shadow: 0 0 5px rgba(0, 0, 0, 0.377);
  padding: 5px 10px 5px 10px;
  border-radius: 16px;
  margin: 10px 10px 15px 0px;
  background: rgb(202, 158, 230);
  background: linear-gradient(45deg, rgba(202, 158, 230, 1) 0%, rgba(245, 194, 231, 1) 43%, rgba(180, 190, 254, 1) 80%, rgba(137, 180, 250, 1) 100%);
  background-size: 300% 300%;
  animation: gradient 10s ease infinite;
  color: #fff;
}


@keyframes gradient {
  0% {
    background-position: 0% 50%;
  }

  50% {
    background-position: 100% 50%;
  }

  100% {
    background-position: 0% 50%;
  }
}


tooltip.background {
  background-color: rgba(00, 00, 00, 0.5);
  font-size: 18px;
  border-radius: 10px;
  color: #FDFDFD;
}

tooltip * {
  padding: 4px;
  background-color: transparent;
  color: white;
}

.host tooltip {
  background-color: rgba(255, 00, 00, 0.5);
}

.popup-clock {
  font-weight: bolder;
  background: rgb(36, 39, 58);
  border-radius: 10px;
}

.popup-clock .calendar-clock {
    color: #d8dee9;
    font-size: 2.5em;
    padding-bottom: 0.1em;
}

.popup-clock .calendar {
    background-color: #2e3440;
    color: @color_text;
    border-radius: 10px;
}

.popup-clock .calendar .header {
    padding-top: 1em;
    border-top: 1px solid @color_border;
    font-size: 1.5em;
}

```
