### ISSUE TITLE
Launcher not starting applications in git version

### ISSUE THREAD

**Issue by Ithvr** [JakeStanger/ironbar#532]
**Describe the bug**
When running the git version of Ironbar the icons in do not start an applications. The icon works (stuff like grouping of window) as normal once I have started the application.

**To Reproduce**
1. Use got version of Ironbar
2. Have launcher added in config
3. Try to use the application icon to start an application 
4. No action happens

**Expected behavior**
For the relevant application to start when clicked on

**System information:**
 - Distro: NixOS Unstable + Flake
- Compositor: LabWC
 - Ironbar version: ironbar-0.15.0-pre+date=2024-04-05_4a3bca1

**Configuration**

<details><summary>Config</summary>
...

{
    "anchor_to_edges": true,
    "icon_theme": "Tela-circle",
    "position": "bottom",
    
    "start": [
      {
        "type": "launcher",
        "favorites": [
          "firefox",
          "thunar",
          "code-url-handler",
          "Alacritty",
          "WebCord",
          "Element"
        ],
        "show_icons": true,
        "show_names": false
      }
    ],
    "end": [
      {
        "type": "tray",
        "direction": "left_to_right"
      },
      {
        "type": "custom",
        "bar": [
          {
            "label": "",
            "name": "power-btn",
            "on_click": "popup:toggle",
            "type": "button"
          }
        ],
        "class": "power-menu",
        "popup": [
          {
            "orientation": "vertical",
            "type": "box",
            "widgets": [
              {
                "label": "Power Menu",
                "name": "header",
                "type": "label"
              },
              {
                "type": "box",
                "widgets": [
                  {
                    "class": "power-btn",
                    "label": "<span font-size='40pt'></span>",
                    "on_click": "!shutdown now",
                    "type": "button"
                  },
                  {
                    "class": "power-btn",
                    "label": "<span font-size='40pt'></span>",
                    "on_click": "!reboot",
                    "type": "button"
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "type": "volume",
        "format": "{icon}",
        "max_volume": 100,
        "icons": {
          "volume_high": "󰕾",
          "volume_medium": "󰖀",
          "volume_low": "󰕿",
          "muted": "󰝟"
        }
      },
      {
        "type": "upower",
        "format": "{percentage}%"
      },
      {
        "type": "clock"
      }
    ]
  }

...
</details>

<details><summary>Styles</summary>

```css

@define-color color_bg #24273a;
@define-color color_bg_dark #1c1c1c;
@define-color color_border #1e2030;
@define-color color_border_active #b7bdf8;
@define-color color_text #cad3f5;
@define-color color_urgent #eed49f;

/* -- base styles -- */

* {
    font-family: Noto Sans Nerd Font, sans-serif;
    font-size: 18px;
    border: none;
    border-radius: 0;
}

box, menubar, button {
    background-color: @color_bg;
    background-image: none;
    box-shadow: none;
}

button, label {
    color: @color_text;
}

button:hover {
    background-color: @color_bg_dark;
}

scale trough {
    min-width: 1px;
    min-height: 2px;
}

#bar {
    border-top: 1px solid @color_border;
}

.popup {
    border: 1px solid @color_border;
    padding: 1em;
}


/* -- clipboard -- */

.clipboard {
    margin-left: 5px;
    font-size: 1.1em;
}

.popup-clipboard .item {
    padding-bottom: 0.3em;
    border-bottom: 1px solid @color_border;
}


/* -- clock -- */

.clock {
    font-weight: bold;
    margin-left: 5px;
}

.popup-clock .calendar-clock {
    color: @color_text;
    font-size: 2.5em;
    padding-bottom: 0.1em;
}

.popup-clock .calendar {
    background-color: @color_bg;
    color: @color_text;
}

.popup-clock .calendar .header {
    padding-top: 1em;
    border-top: 1px solid @color_border;
    font-size: 1.5em;
}

.popup-clock .calendar:selected {
    background-color: @color_border_active;
}


/* -- launcher -- */

.launcher .item {
    margin-right: 4px;
}

.launcher .ifix examtem:not(.focused):hover {
    background-color: @color_bg_dark;
}

.launcher .open {
    border-bottom: 1px solid @color_text;
}

.launcher .focused {
    border-bottom: 1px solid @color_border_active;
}

.launcher .urgent {
    border-bottom-color: @color_urgeAlacritty's configuration file uses the TOML format. The format's specification can be found at https://toml.io/en/v1.0.0.nt;
}

.popup-launcher {
    padding: 0;
}

.popup-launcher .popup-item:not(:first-child) {
    border-top: 1px solid @color_border;
}


/* -- music -- */

.music:hover * {
    background-color: @color_bg_dark;
}

.popup-music .album-art {
    margin-right: 1em;
}

.popup-music .icon-box {
    margin-right: 0.4em;
}

.popup-music .title .icon, .popup-music .title .label {
    font-size: 1.7em;
}

.popup-music .controls *:disabled {
    color: @color_border;
}

.popup-music .volume .slider slider {
    border-radius: 100%;
}

.popup-music .volume .icon {
    margin-left: 4px;
}

.popup-music .progress .slider slider {
    border-radius: 100%;
}

/* -- script -- */

.script {
    padding-left: 10px;
}


/* -- sys_info -- */

.sysinfo {
    margin-left: 10px;
}

.sysinfo .item {
    margin-left: 5px;
}


/* -- tray -- */

.tray {
    margin-left: 10px;
}


/* -- workspaces -- */

.workspaces .item.focused {
    box-shadow: inset 0 -3px;
    background-color: @color_bg_dark;
}

.workspaces .item:hover {
    box-shadow: inset 0 -3px;
}


/* -- custom: power menu -- */

.popup-power-menu #header {
    font-size: 1.4em;
    padding-bottom: 0.4em;
    margin-bottom: 0.6em;
    border-bottom: 1px solid @color_border;
}

.popup-power-menu .power-btn {
    border: 1px solid @color_border;
    padding: 0.6em 1em;
}

.popup-power-menu #buttons > *:nth-child(1) .power-btn {
    margin-right: 1em;
}

```
</details>
