### ISSUE TITLE
XDG menu

### ISSUE THREAD

**Issue by ClaireNeveu** [JakeStanger/ironbar#534]
**Is your feature request related to a problem? Please describe.**
The Launcher module is great for frequently accessed programs but right now ironbar doesn't provide a solution to infrequently used programs that you don't want cluttering the bar all the time. You mentioned in https://github.com/JakeStanger/ironbar/issues/194 that you don't really want to embed a rofi-like menu (like KDE does) but would you be open to a customizable XDG menu sort of like XFCE?

![xdg-menu](https://github.com/JakeStanger/ironbar/assets/1002726/7ed77b36-91f9-48c3-886c-13439fb71259)

**Describe the solution you'd like**
The interface would be something like:
```yaml
 - type: menu
   xdg_menu: true
   before:
   - label: Run Program
     action: "wofi --show drun"
   - label: Terminal
     action: "xterm"
   after:
   - label: logout
     action: "wlogout"
```

**Describe alternatives you've considered**
I've thought about building something with the custom modules but you can't dynamically decide which GTK elements are present.

**Additional context**
I'd be willing to contribute the module to ironbar if the idea is acceptable.
