### ISSUE TITLE
Tray icon color channels are being incorrectly rendered

### ISSUE THREAD

**Issue by rdnelson** [JakeStanger/ironbar#546]
**Describe the bug**
The tray module is incorrectly rendering the color channels of the pixmaps provided by applications with tray icons.

**To Reproduce**

1. Update the config to include the tray module (very large icons make it easier to see)
   ```yaml
   type: tray
   icon_size: 128
   prefer_theme_icons: false
   ```
2. Observe the tray icon in detail, and notice that it does not appear the same as the original icon viewed in an image viewer.

**Expected behavior**
The tray icon should be rendered the same way an image viewer would.

**System information:**
- Distro: Arch Linux
- Compositor: Hyprland
 - Ironbar version: f4e1e81

**Configuration**
```yaml
start: []
center: []
end:
  - type: tray
    icon_size: 128
    prefer_theme_icons: true
```

**Additional context**
The GTK documentation [here](https://docs.gtk.org/gdk-pixbuf/class.Pixbuf.html#image-data) shows that the internal representation of their pixel data is RGBA, instead of the ARGB data that's being handled by `modules/tray/icon.rs::get_image_from_pixmap`

**Screenshots**
Rendered Icon:
![2024-04-21T19:02:39,174565917-04:00](https://github.com/JakeStanger/ironbar/assets/1231364/bb20eaf0-bf98-4754-b98e-edb36a5f45d8)

Original Icon (Before it was scaled to 22x22 and back):
![logo](https://github.com/JakeStanger/ironbar/assets/1231364/ff01c5b3-77a0-4320-af7b-ba9a117d8df8)
