### ISSUE TITLE
Focused module doesn't work but only on deadbeef when last is opened 

### ISSUE THREAD

**Issue by DanteDragan** [JakeStanger/ironbar#554]
**Describe the bug**
Focused disappears right after focusing on new window after deadbeef. After closing deadbeef all is working properly. 

**To Reproduce**
Open deadbeef with plugin **Customizable toolbar for GTKUI(GTK3)** and setting `GUI/Misc -> Player -> Titlebar text while playing: ` set to `%artist% - %album% (%year%) - %title% - %playback_time% / %length% `

**Expected behavior**
Focused is working ok with deadbeef open

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland
 - Ironbar version: 0.15.0-pre

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```
{
  "position": "bottom",
  "height": 42,
  "start": [
    {
      "type": "launcher",
      "favourites": [
        "vivaldi"
      ],
      "show_names": false,
      "show_icons": true
    },
    {
      "type": "workspaces"
    }
  ],
  "center": [
    {
      "type": "focused",
      "show_icon": true,
      "show_title": true,
      "icon_size": 32,
      "truncate": "end"
    },
    {
      "type": "music",
      "player_type": "mpris",
      "format": "{artist} - {album} - {title}",
      "truncate": "end",
      "icon_size": 32,
      "icons": {
        "play": "",
        "pause": ""
      }
    }
  ],
  "end": [
    {
      "type": "clock",
      "format": "%d/%m/%Y\n%H:%M"
    },
    {
      "type": "volume",
      "format": "{icon} {percentage}%",
      "max_volume": 100,
      "icons": {
        "volume_high": "",
        "volume_medium": "",
        "volume_low": "",
        "muted": ""
      }
    },
    {
      "type": "clipboard",
      "icon": "",
      "max_items": 3,
      "truncate": {
        "mode": "end",
        "length": 50
      }
    },
    {
      "type": "tray",
      "icon_size": 50,
      "prefer_theme_icons": true
    },
    {
      "type": "notifications",
      "show_count": true,
      "icons": {
        "closed_none": "󰍥",
        "closed_some": "󱥂",
        "closed_dnd": "󱅯",
        "open_none": "󰍡",
        "open_some": "󱥁",
        "open_dnd": "󱅮"
      }
    }
  ]
}

```
</details>

<details><summary>Styles</summary>

```css
* {
  font-family:
    Noto Sans Nerd Font,
    sans-serif;
  font-size: 14px;
  border: none;
  border-radius: 0px;
  margin-right: 2px;
  margin-left: 2px;
}

menubar,
button {
  border-radius: 33px;
}
.background {
  background: rgba(0, 0, 0, 0);
}
.popup {
  background: rgba(255, 255, 255, 255);

}
.focused {
  margin-right: 15px;
}
.focused .label {
  color: rgba(255, 255, 255, 255);
}

```
</details>

**Additional context**
I've waybar also installed.

**Screenshots**
https://disk.yandex.ru/i/eRkrIC09gkkPJg

**Log**
[ironbar_log.log](https://github.com/JakeStanger/ironbar/files/15080503/ironbar_log.log)
