### ISSUE TITLE
OS error 2

### ISSUE THREAD

**Issue by madfanat** [JakeStanger/ironbar#594]
**Describe the bug**
Today I installed all available updates and then restarted my computer. Everything works fine, but ironbar won't start. Here is the output I am getting::
```
$ RUST_BACKTRACE=1 ironbar
2024-05-18T13:40:30.562133Z  INFO ironbar: 115: Ironbar version 0.16.0-pre
2024-05-18T13:40:30.562143Z  INFO ironbar: 116: Starting application

(ironbar:1810): dbind-WARNING **: 16:40:30.588: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2024-05-18T13:40:30.611897Z  INFO ironbar::ipc::server: 37: Starting IPC on /run/user/1000/ironbar-ipc.sock
2024-05-18T13:40:30.612721Z  INFO ironbar::bar: 118: Initializing bar 'bar-5' on 'DP-2'
2024-05-18T13:40:30.614477Z  INFO ironbar::clients::compositor::hyprland: 32: Starting Hyprland event listener
2024-05-18T13:40:30.614708Z ERROR ironbar: 203:
   0: zbus error
   1: I/O error: Нет такого файла или каталога (os error 2)
   2: Нет такого файла или каталога (os error 2)

Location:
   src/clients/mod.rs:121

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**To Reproduce**
1.Type `paru -Syu`
2. Restart a computer
3. See error

**System information:**
 - Distro: Artix Linux
- Compositor: Hyprland 0.40.0-1
 - Ironbar version: ironbar-git v0.15.1.r22.g47e3e0f-1

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```corn
let {
	$workspaces = {
		type = "workspaces"
	}
	
	$launcher = {
		type = "launcher"
		favorites = [
		    "org.gnome.Nautilus"
			"thorium-browser"
		    "alacritty"
		    "transmission-gtk"
		    "steam" 
		    "net.lutris.Lutris"
		    "org.prismlauncher.PrismLauncher"
	        "telegram-desktop"
		]
	}

	$notifications = {
	    type = "notifications"
        show_count = true
        icons.closed_none = "󰂜"
        icons.closed_some = "󰂜"
        icons.closed_dnd = "󰪓"
        icons.open_none = "󰂚"
        icons.open_some = "󰂚"
        icons.open_dnd = "󰂠"
    }

	$tray = {
		type = "tray"
		direction = "left_to_right"
		icon_size = 20
	}

	$clock = {
		type = "clock"
		format = "%d.%m.%Y %H:%M"
	}

	$volume = {
        type = "volume"
        format = "{icon} {percentage}%"
        max_volume = 100
        icons.volume_high = " "
        icons.volume_medium = ""
        icons.volume_low = ""
        icons.muted = " "
	}

	$button = { type = "button" name="power-button" label = "<span font-size='20pt'>󰐥</span>" on_click = "popup:toggle" }

    $popup = {
        type = "box"
        orientation = "horizontal"
        widgets = [
            {
                type = "box"
                widgets = [
                    { type = "button" class="power-button" label = "<span font-size='20pt'>󰐥</span>" on_click = "!loginctl poweroff" }
                    { type = "button" class="power-button" label = "<span font-size='20pt'>󰜉</span>" on_click = "!loginctl reboot" }
					{ type = "button" class="power-button" label = "<span font-size='20pt'>󰤄</span>" on_clock = "!loginctl suspend" }
                ]
            }
        ]
    }

    $power_menu = {
        type = "custom"
        class = "power-menu"

        bar = [ $button ]
        popup = [ $popup ]
    }

}

in {
    anchor_to_edges = true
	icon_theme = "Papirus-Dark"
	start = [ $power_menu $workspaces ]
	center = [ $launcher ]
	end = [ $tray $volume $clock $notifications ]
}

```
</details>

<details><summary>Styles</summary>

```css
@import "mocha.css";

/* -- general configuration -- */

* {
    font-family: "JetbrainsMono Nerd Font";
    font-size: 16px;
    border: none;
    border-radius: 18px;
}

#bar {
    border-top: 1px solid @surface0;
}

box, menubar, button {
    background-image: none;
    box-shadow: none;
}

box, menubar {
    background-color: @base;
}

button {
    background-color: @surface0;
    padding: 0 5px;
}

button, label {
    color: @text;
}

button:hover {
    background-color: @surface2;
}

.popup {
    padding: 1em;
    border: 1px solid @surface0;
}

/* -- workspaces configuration */

.workspaces	{
    background-color: @surface0;
    margin-left: 5px;
}

.workspaces .item {
    background-color: @surface0;
    border-radius: 100%;
}

.workspaces .item:not(:first-child) {
    margin-left: 4px;
}

.workspaces .item.focused {
    background-color: @surface1;
}

.workspaces .item:hover {
    background-color: @surface2;
}

/* -- launcher configuration -- */

.launcher {
    margin-left: 5px;
}

.launcher .item {
    background-color: @base;
    padding: 0 5px;
    border-radius: 100%;
}

.launcher .item:not(:first-child) {
    margin-left: 4px;
}

.launcher :hover {
    background-color: @surface2;
}

.launcher .open {
    background-color: @surface1;
}

.launcher .focused {
    background-color: @surface2;
}

.launcher .urgent {
    background-color: @red;
}

.popup-launcher {
    padding: 5px;
}

.popup-launcher .popup-item:not(:first-child) {
    margin-top: 5px;
}

/* -- clock configuration -- */

.clock {
    font-weight: bold;
    margin-left: 5px;
    margin-right: 5px;
}

.popup-clock .calendar-clock {
    color: @text;
    font-size: 2.5em;
    margin-bottom: 5px;
    padding-left: 5px;
    padding-right: 5px;
    background-color: @surface0;
}

.popup-clock .calendar {
    background-color: @surface0;
    color: @text;
}

.popup-clock .calendar .header {
    font-size: 1.5em;
}

.popup-clock .calendar:selected {
    background-color: @rosewater;
    color: @base;
}

/* -- notifications configuration -- */

.notifications {
    border-radius: 100%;
}

.notifications .count {
    font-size: 0.6rem;
    background-color: @text;
    color: @crust;
    border-radius: 100%;
    margin-right: 3px;
    margin-top: 3px;
    padding-left: 4px;
    padding-right: 4px;
    opacity: 0.7;
}

/* -- tray configuration -- */
.tray {
   background-color: @base; 
}

.tray .item:hover {
    background-color: @surface2;
}

.tray .item:not(:first-child) {
    margin-left: 4px;
}

/* -- volume configuration -- */
.volume {
    margin-left: 5px;
}

.popup-volume .device-box .device-selector {
    background-color: @surface0;
}

.popup-volume .device-box .slider	{
    background-color: @surface0;
}

/* -- powermenu configuration -- */

.power-menu #power-button {
    padding: 0 13px;
    border-radius: 100%;
    
}

.popup-power-menu {
    padding: 5px;
}

.popup-power-menu .power-button {
    padding: 0 10px;
    border-radius: 100%;
    margin: 0 2.5px;
}


```
</details>
