### ISSUE TITLE
Notifications module's count indicator is unclickable

### ISSUE THREAD

**Issue by ToxicMushroom** [JakeStanger/ironbar#620]
**Describe the bug**
The number indicator for the notifications module essentially blocks the button under it.

**To Reproduce**
1. Have swaync and, ironbar with notifications module
2. Have at least 1 notification 
3. Try opening/closing the menu by clicking on the notification count

**Expected behavior**
With mouse above the on the notification count should imo also toggle the module's click, scroll or other  events. The current behavior make it look like the module sometimes doesn't work, because you clicked on an unfortunate location.

Furthermore, when styling the notification count to make it a little bigger (as its quite small by default with my gtk theme) this issue becomes worse.

**System information:**
 - Distro: Arch Linux
 - Compositor: Sway 1.9
 - Ironbar version: 1.6.0-pre

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```toml
[[end]]
type = "notifications"
show_count = true

[end.icons]
closed_none = "󰍥"
closed_some = "󱥂"
closed_dnd = "󱅯"
open_none = "󰍡"
open_some = "󱥁"
open_dnd = "󱅮"
```
</details>

<details><summary>Styles</summary>

```css
/* notifications */

.notifications .count {
    font-size: 1rem;
    background-color: coral;
    color: white;
    border-radius: 100%;
    margin-right: 3px;
    margin-top: 3px;
    padding-left: 6px;
    padding-right: 6px;
    padding: 1px 6px;
    opacity: 1;
}
```
</details>

**Screenshots**

https://github.com/JakeStanger/ironbar/assets/32853531/e62006b5-63d5-4701-8e5c-6838805f2e5a
