### ISSUE TITLE
Favourite-Workspace that was focused during start of ironbar disappears when switching to a different workspace

### ISSUE THREAD

**Issue by Lxtharia** [JakeStanger/ironbar#705]
**Describe the bug**
When adding favorites in the workspace module, the workspaces that were active when ironbar starts disappear when empty or emptied and I'm switching to a different workspace on that screen.
They _stay_ hidden when trying to switch back.

**To Reproduce**
1.
  ```toml
  [[start]]
  type = "workspaces"
  favorites = [ "1", "2" ]
  ```
2. switch to workspace 1 
3. Open something on ws-1
4. start ironbar
 => ws-1 stays visible because something is open
5. close whatever is on workspace 1
6. switch to another workspace on that screen
=> workspace 1 disappears even though it is listed in favourites
7. switch back to empty workspace 1 and open something
=> workspace 1 _stays_ hidden, even though it should not

**Expected behavior**
All workspaces listed in the favorites array should be visible in the bar at all times, even when empty.

**System information:**
 - Distro: Arch Linux
 - Compositor: Sway
 - Ironbar version: 0.16.1-pre

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```toml
position = "top"
height = 24

[[start]]
type = "workspaces"
# all_monitors = false
# favorites = { "DVI-D-1"=[ "1", "2", "3", "4" ] }
favorites = [ "1", "2" ]

center=[]

[[end]]
type = "tray"
direction = "right_to_left"

[[end]]
type = "music"
format = "{title}"

[[end]]
type = "clock"
format = "%d/%b/%Y | %H:%M:%S"

[[end]]
type = "notifications"
show_count = true

```
</details>

issue persists even when using no stylesheet

**Additional context**

**Screenshots**
