### ISSUE TITLE
How to style Notification button

### ISSUE THREAD

**Issue by Humorist2601** [JakeStanger/ironbar#728]
Hello

Recently tried you bar and I am loving it. Just one thing. I have tried customizing the notification button using following css
```css
.notifications {
  border-radius: 0;
}
```

But it is still showing the border radius. Any help

**Comment by JakeStanger** [comment]
I'm not sure why that wouldn't work. It may be a specificity issue. Try specifying it's the button you're after:

```css
button.notifications {
  border-radius: 0;
}
```

If still no luck, let me know and I'll give it a go as soon as I can.
