### ISSUE TITLE
`ironbar bar <name> hide` doesn't hide all bars by the same name

### ISSUE THREAD

**Issue by zeroeightysix** [JakeStanger/ironbar#770]
Hi, glad to see this project has evolved so well :)
I'm finally trying to move from swaybar, but:

With a simple config on a multimonitor setup:

```toml
name = "bar"
start = []
center = []
end = []
```

invoking the cli to hide the bar that is on multiple monitors:

`ironbar bar bar hide`

only hides a bar on a single monitor, instead of all.
