### ISSUE TITLE
Is there a way to theme .popup-clock .calendar

### ISSUE THREAD

**Issue by avc-mbcet** [JakeStanger/ironbar#830]
Is there a way to theme GtkCalendar widget's current day, days of the week, month, year etc

**Comment by JakeStanger** [comment]
You are able to theme the selected day like so:

```css
.popup-clock .calendar:selected {
    background-color: red;
}
```

Unfortunately GTK3 does not offer any of the other capabilities, so this will need to either wait for a GTK4 port or a custom calendar widget being developed.

See #244/#255 for more discussion on this.
