### ISSUE TITLE
Tray issues

### ISSUE THREAD

**Issue by p00f** [JakeStanger/ironbar#84]
**Describe the bug**
When I use the tray icon from `nm-applet`,
1) The icons don't get updated (for example the icon should become a lock when a VPN is enabled but this doesn't happen until I restart the bar)

2) There are no checkboxes (each of the three vpn connections is supposed to have a checkbox to its left)
![Screenshot from 2023-03-19 at 16_37_27 951359431](https://user-images.githubusercontent.com/36493671/226171426-c1556dc4-beda-45b8-a336-30d3a2880cfd.png)

3) The bar crashes after some time of interacting with tray items:
https://paste.sr.ht/~p00f/6c6afbfd14a1aacaee2ba6d49cb9e582323eded4

4) Clicking buttons doesn't work in the main dropdown

**To Reproduce**
1. Run `nm-applet --indicator`
2. Right click the tray item, "Enable networking" and "Enable Wi-Fi" don't have checkboxes next to them.
3. Clicking "enable networking" doesn't toggle network (clicking vpn connections > some connection does toggle that connect though)
4. Interact with the menu items for some time, the bar crashes

**System information:**
 - Distro: Arch Linux
- Compositor: River
 - Ironbar version: d4dd8 + my upower commit (I hope that's not relevant)

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```yaml2
position: "top"
height: 25
start:
  - type: "focused"
    show_icon: true
    show_title: true
    truncate: "end"
center:
  - type: "clock"
    format: "%a %d            %H:%M"
end:
  - type: "upower"
    format: "icon:{icon} {percentage}%"
  - type: "tray"

```
</details>

<details><summary>Styles</summary>

```css
.background {
    background-color: black;
}

#bar {
    background-color: black;
}


#focused {
    font-size: 17px;
    font-weight: bold;
}

#clock {
    font-size: 17px;
    font-weight: bold;
}

```
</details>
