### ISSUE TITLE
Crashing on pulseaudio

### ISSUE THREAD

**Issue by ToxicMushroom** [JakeStanger/ironbar#875]
**Describe the bug**
I don't know why this happens

**To Reproduce**
:c 

**Expected behavior**
No crashes

**System information:**
 - Distro: 6.13.3-arch1-1 
 - Compositor: niri 25.01 (v0.1.10-245-g81824845)
 - Ironbar version: ironbar 0.16.1-pre

**Configuration**
Irrelevant I assume
Maybe you need to have the volume or mpd module ?
Added on request*
<details><summary>Config</summary>

```toml
merlijn@mimic ~ % cat .config/ironbar/config.toml
anchor_to_edges = true
height = 42
position = "top"
icon_theme = "Papirus-Dark"

#[[start]]
#type = "workspaces"
#all_monitors = false
#on_scroll_up = "swaymsg workspace prev_on_output"
#on_scroll_down = "swaymsg workspace next_on_output"

#[[start]]
#type = "sway_mode"

[[end]]
type = "script"
cmd = "/home/merlijn/.bin/iron-bluetooth.sh"
mode = "poll"
interval = 5000
on_click_left = "blueman-manager"

[[end]]
type = "music"
player_type = "mpd"
truncate = "end"


[[end]]
type = "sys_info"
format = [
    "  {cpu_percent}% - {temp_c:k10temp-Tccd1}°C |",
    "  ({memory_percent}%) |",
    "󰋊 ({disk_percent:/}%) |",
    "󰓢 {net_down:enp5s0} / {net_up:enp5s0} Mbps |",
]

[end.interval]
memory = 30
cpu = 1
temps = 5
disks = 300
networks = 3

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 100

[end.icons]
volume_high = "󰕾"
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"

[end.truncate]
mode = "end"
length = 50


[[end]]
type = "clock"
format = "  %H:%M:%S %d/%m/%Y"

[[end]]
type = "tray"
# direction = "left_to_right"

[[end]]
type = "notifications"
show_count = true

[end.icons]
closed_none = "󰍥"
closed_some = "󱥂"
closed_dnd = "󱅯"
open_none = "󰍡"
open_some = "󱥁"
open_dnd = "󱅮"
```
</details>

**Additional context**
Last log lines before crash:
```
Assertion 'm->cached_next_time_event->enabled' failed at ../pulseaudio/src/pulse/mainloop.c:342, function mainloop_time_new(). Aborting.
Assertion 't = find_next_time_event(m)' failed at ../pulseaudio/src/pulse/mainloop.c:740, function calc_next_timeout(). Aborting.
```
- I'm not interacting with the bar directly when this happens.
- I am changing videos in `tagstudio` frequently which removes and creates a new playback stream in pulse.
