### ISSUE TITLE
Help: Unwanted flat color box around workspace number

### ISSUE THREAD

**Issue by xaviduds** [JakeStanger/ironbar#914]
Hello, how can i remove that box around the number in the workspace?
I tried messing with height, went to default style, padding 0 erased box-shadow as expected i think

The result: 

![Image](https://github.com/user-attachments/assets/68cadc81-7a59-47ba-861b-28b271276a1d)

My style.css (i changed to accentuate the box):

```css
* {
    background: #1e1e2e;
    color: #cdd6f4;
    border: none;
    box-shadow: none;
}
.workspaces * {
    background: #1e1e2e;
    color: #cdd6f4;
}
.workspaces .item:hover {
    box-shadow: inset 1 1 4 1;
    color: #89b4fa;
}
.workspaces .item.focused {
    box-shadow: inset 1 1 6 1;
    color: #cba6f7;
}
```

**Comment by JakeStanger** [comment]
Try targeting the label itself. Something like:

```css
.workspaces .item label {
  background-color: #00000000
}
```

If you run `ironbar inspect` that will show you to the widget tree and CSS selectors which can make life a bit easier.

If that doesn't work give me a shout and I'll have a deeper dive when I can.
