### ISSUE TITLE
Clock text points in a different direction from all other widgets?

### ISSUE THREAD

**Issue by cyrneko** [JakeStanger/ironbar#947]
**Describe the bug**
In a vertical bar setup, all the widgets I enabled with text (volume, clipboard) have the text point to the left of my screen, with the bar being on the right

the clock, for some reason, has it's text point to the right

**To Reproduce**

1. Add module `clock`
2. Add module `volume`
3. see the text being flipped/rotated differently for each widget

**Expected behavior**

Both the clock and volume text should point the same direction / have the same rotation.

**System information:**
 - Distro: Fedora 42
- Compositor: Niri (git, commit `7884d3bf`)
 - Ironbar version: git, commit `a9508e65`

**Configuration**

<details><summary>Config</summary>

```
position: "right"
height: 32
start:
  - type: "workspaces"
center: []
end: 
  - type: "volume"
  - type: "clipboard"
    max_items: 3
    truncate:
      mode: 'end'
      length: 50
  - type: "tray"
    icon_size: 32
  - type: "notifications"
  - type: "clock"
    format: "%H:%M"
    orientation: vertical
```
</details>

**Additional context**
N/A

**Screenshots**

![Image](https://github.com/user-attachments/assets/ccd37796-23fd-457c-9a29-4299f4a79e5f)

Notice the Clock and Volume text has different rotation.
