### ISSUE TITLE
(Re upload) Worspace buttons disappear

### ISSUE THREAD

**Issue by lordmujin** [JakeStanger/ironbar#964]
**Describe the bug**
When switching workspaces, after hyprland and ironbar start, if I switch to another workspace, the one I was at the start vanishes. If I do `ironbar reload` it goes back to normal but the behavior repeats.

Duplicate of: https://github.com/JakeStanger/ironbar/issues/464
 
**To Reproduce**
Set favorite workspaces, start hyprland in this case, switch workspaces, and sometimes it works correctly, but fails more often.

**Expected behavior**
That all favorite workspaces are persistent

**System information:**
 - Distro: NixOS
- Compositor: Hyprland
 - Ironbar version: 0.16.1 (nix-unstable)

**Configuration**

<details><summary>Config</summary>

```
{ "type": "workspaces",
		  "name_map": {
  		  	"1": "一",
  		  	"2": "二",
  		  	"3": "三",
  		  	"4": "四",
  		  	"5": "五"
  		  },
		  "favorites": ["1", "2", "3", "4", "5"],
		  "hidden": ["special:scratch_music", "special:scratch_term", "special:special"]
  		}
```
</details>

<details><summary>Styles</summary>

```css
.workspaces {
	margin-left: 10px;
}

.workspaces .item.focused {
	color: @blue;
	background-color: @gray-dark;
    box-shadow: inset 0 -3px;
}

.workspaces .item.urgent {
    background-color: @red;
}

.workspaces .item:hover {
	color: @sky;
	background-color: @base;
    box-shadow: inset 0 -3px;
}
```
</details>

**Additional context**
[](https://github.com/JakeStanger/ironbar/issues/464)

**Screenshots**
