### ISSUE TITLE
[Workspaces] CSS selector for non-visible workspaces that do have windows

### ISSUE THREAD

**Issue by vtsionis** [JakeStanger/ironbar#979]
After searching through open and closed issues I couldn't find something related to my request.

In the documentation for the Workspaces module, you can use the `.workspaces .item.visible` and the `.workspaces .item.focused` CSS selectors to target the corresponding workspace(s).

But how about targeting a non-visible workspace that does have an open window at the moment? Something like `.workspaces .item.active` or similar concept. I am not sure if that is even technically possible but I would love to know your opinion on this.

**Comment by postsolar** [comment]
```css
.workspaces > .item:not(.visible) {
  background: green;
}
```
Is it this or am I misunderstanding something?

**Comment by vtsionis** [comment]
@postsolar Although that is pure CSS selectors mastery, unfortunately not what I am looking for.
Let me add some screenshots to clarify the case in point.

This is the current behavior with workspace `11` being focused:
```css
.workspaces .item.focused {
  background-color: #50FA7B;
  color: #282A36;
 }
```

![Image](https://github.com/user-attachments/assets/59d18a1b-ff34-4256-a975-e620e5f14025)

Let's say that I also have one or more windows open in workspaces `12` and `14`, while the focused workspace is still `11`. Then the module would ideally look something like this:

![Image](https://github.com/user-attachments/assets/34401b07-913c-4030-ba8c-a675cd86f8e3)

with the corresponding (draft) CSS:
```css
.workspaces .item.active {
  background-color: #BD93F9;
  color: #21222C;
}
```

In comparison to @postsolar's snippet, which would look something like this:

![Image](https://github.com/user-attachments/assets/9981ea47-fa72-44b4-839b-54d2669c28ea)

I hope that my request is now a bit more clear with the provided screenshots.

**Comment by JakeStanger** [comment]
Although it *is* the opposite of the `inactive` selector, I'm not sure I like `active` as a name, as it's easily confused with the existing `focused`.

That's given me an idea though...

If I'm understanding correctly, you could view what you're after as selecting everything BUT inactive workspaces. So you could adapt postsolar's idea:

```css
.workspaces > .item:not(.inactive) {
  background: green;
}
```

If you need to be more specific to avoid clashing with `focused`, you can chain another `:not` on the end (I think)

```css
.workspaces > .item:not(.inactive):not(.focused) {
  background: green;
}
```

**Comment by vtsionis** [comment]
Unfortunately still not what I am going for.

Full disclosure, I am using a Hyprland plugin called `split-monitor-workspaces` which allows me to have a set of 10 workspaces per monitor (1 to 10 on monitor A and 11 to 20 on monitor B) which are also always visible regardless if they have an open window on them or not. Basically, it is similar to how AwesomeWM handles workspaces. So I don't know if my setup complicates things.

In the below screenshot, I have at least one open window on:
- worksace 1 (visible on monitor A) targeted by `.visible` class
- workspace 4
- worspaces 11 (visible on monitor B, and the mouse cursor is on it) targeted by `.focused` class
- workspace 12

which with the below `style.css`  snippet:

```css
.workspaces {
  background-color: @BG;
  border: 1px solid @BORDER;
}
.workspaces .item.visible {
  background-color: @SECONDARY;
  color: @BGD;
}
.workspaces .item.focused {
  background-color: @ACTIVE;
  color: @BG;
}
```
produce this end result:

![Image](https://github.com/user-attachments/assets/bcd27c21-0871-4ec1-85ad-72121effbae6)

Now what I would like to have is a class that targets workspace 4 and 12 that do have an open window but are not visible nor focused. I also agree that `.active` is not a good choice but as we know, naming things is hard. Maybe something like `.non-empty`? Just a thought.

**Comment by JakeStanger** [comment]
Current plan is to add a new `.populated class name. Use-case has increased with Niri gaining traction.

**Comment by carmanaught** [comment]
I don't know if you already found this out yourself @vtsionis, but I've been trying to style labels the same way and I've found that as long as you set the styling you want on the relevant states including the base `.item`, I think you can get the styling you want. I'm also putting this here for anyone else coming across this, since I was trying to achieve the same thing.

Specifically, the `.workspaces .item` affects the items generally, so you can treat that as your "workspace populated but not active or empty", then make sure that the `.workspaces .item.inactive` and `.workspaces .item.focused` are set.

I think what you're wanting should work like this (assuming some color choices here):
```css
.workspaces .item {
  background-color: #BD93F9;
  color: #21222C;
}
.workspaces .item.inactive {
  background-color: unset;
  color: #FFF;
}
.workspaces .item.focused {
  background-color: #50FA7B;
  color: #282A36;
}
```

That said, it will be best to have the specific `.populated` class name to target the relevant workspaces, rather than applying styling to the base `.item`.
